### ISSUE TITLE
AttributeError: module 'igraph' has no attribute 'VertexClustering'

### ISSUE THREAD

**Issue by amandaoliver15** [YosefLab/Compass#55]
Hi there, I get this error when trying to run Compass, tried uninstalling and reinstalling igraph but this did not help. Any idea how to fix this? Thanks!

**Comment by schel337** [comment]
What version of igraph is installed?

**Comment by amandaoliver15** [comment]
igraph-0.9.8 python-igraph-0.9.8

**Comment by schel337** [comment]
I have not been able to replicate this, Compass microclustering works on my windows boot with igraph-0.9.8 and leidenalg 0.8.8. I would guess leidenalg is worth trying to reinstall, as Compass only uses igraph through the leiden clustering algorithm (unless scikit-learn's nearest neighbors is using it under the hood). The igraph module also has VertexClustering as an attiribute on my machine.

If you can import igraph in a python console and enter `igraph.VertexClustering` and get `<class 'igraph.clustering.VertexClustering'> ` then it indicates igraph is correctly installed, but Compass is likely installed incorrectly in some way. I would try `pip uninstall compass-sc` and reinstalling it to the same python environment as igraph is installed to (for instance a conda environment if that is where igraph is installed correctly). If igraph does not have a VertexClustering attribute in the python console, it's most likely an installation issue with igraph which I have no particular expertise with beyond their documentation.

**Comment by amandaoliver15** [comment]
Hi, Compass was correctly installed so it was the igraph installation. I solved the problem by uninstalling and reinstalling igraph `pip uninstall igraph` and `python -m pip install python-igraph` _after_ the Compass install. Thanks for your help.

**Comment by schel337** [comment]
I'm glad the issue was resolved.
